spring.application.name=CodeBurgerApi
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DATABASE}
server.port=8080
server.servlet.context-path=/api
springdoc.swagger-ui.path=/swagger