spring.application.name=CodeBurgerApi
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DATABASE}
server.port=${PORT:8080}
server.servlet.context-path=/api
springdoc.swagger-ui.path=/swagger